application: virtualvideoapp
version: 2014-06-09-2310
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /images
  static_dir: client/dist/images

- url: /scripts
  static_dir: client/dist/scripts

- url: /styles
  static_dir: client/dist/styles
  
- url: /bower_components
  static_dir: client/dist/bower_components

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: apprtc.app
  #secure: always

inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.swp$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^client/node_modules/.*
- ^client/.*\.json$
- ^client/test/.*
- ^client/Gruntfile\.js
