application: virtualvideoapp
version: 2014-06-06-2145
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /views
  static_dir: client/app/views

- url: /images
  static_dir: client/app/images

- url: /scripts
  static_dir: client/app/scripts

- url: /styles
  static_dir: client/.tmp/styles
  
- url: /bower_components
  static_dir: client/app/bower_components

- url: /.*
  script: apprtc.app
  #secure: always

inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.swp$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^client/node_modules/.*
- ^client/.*\.json$
- ^client/test/.*
- ^client/Gruntfile\.js
